# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pbgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(343, 302)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 311, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutLetraA_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutLetraA_2.setObjectName("horizontalLayoutLetraA_2")
        self.labelLetraA_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelLetraA_2.setObjectName("labelLetraA_2")
        self.horizontalLayoutLetraA_2.addWidget(self.labelLetraA_2)
        self.doubleSpinBoxLetraA_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBoxLetraA_2.setObjectName("doubleSpinBoxLetraA_2")
        self.horizontalLayoutLetraA_2.addWidget(self.doubleSpinBoxLetraA_2)
        self.verticalLayout.addLayout(self.horizontalLayoutLetraA_2)
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelLetraA_2.setText(_translate("MainWindow", "Letra A:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
